name: article_parser
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0
