name: article_parser
description: Article parser library for internal repository use only
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  yaml: ^3.1.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0
