name: markdown_metadata_cli
description: A CLI tool that extracts metadata from Markdown articles and saves them as yearly JSON files
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  article_models:
    path: ../../packages/article_models

  args: ^2.7.0
  path: ^1.9.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
