name: article_viewer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # routing
  go_router: ^14.8.1

  # annotation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  yaml: ^3.1.3

  # localization
  intl: ^0.20.2

  # ui
  flutter_markdown: ^0.7.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lint
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5
  freezed_lint: ^0.0.9

  # generator
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  go_router_builder: ^2.8.2
  freezed: ^3.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/meta/
    # TODO: deploy pipelineでroot/articles からassets にコピーする
    - assets/articles/2025/01/
