name: article_viewer
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # routing
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.15
  custom_lint: ^0.7.5

  # lint
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5

  # generator
  riverpod_generator: ^2.6.5
  go_router_builder: ^2.8.2
  

flutter:
  uses-material-design: true